version: '3'
services:
  main:
    build: .
    restart: always
    ports:
      - 5000:5000
    networks:
      - internal
#    depends_on:
#      - redis
    environment:
      - TTL=86400

networks:
  internal:
